version: "3.8"
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - network
    ports:
      - 443:443
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - network
    env_file:
      - .env
    restart: always
    ports:
      - 9000:9000

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - network
    env_file:
      - .env
    restart: always

networks:
  network:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/bocal/inceptio/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/bocal/inceptio/wordpress
      o: bind
